package com.notesapp.offline.data

import kotlinx.serialization.Serializable
import java.util.UUID

/**
 * Core note model.
 *
 * A note is either plain-text, a checklist, or a drawing (kept simple —
 * one "mode" per note, matching how the original app's cards render:
 * a note shows a checklist preview OR a drawing thumbnail OR body text).
 *
 * `magicEffectId` links a note to a MagicEffect's force-list — when set,
 * this note's checklist/body is regenerated by the magic engine every time
 * the effect's items change, and the note is hidden from normal search/
 * filter noise by convention (still a real note, just system-managed).
 */
@Serializable
data class Note(
    val id: String = UUID.randomUUID().toString(),
    val title: String = "",
    val body: String = "",
    val styleRuns: List<StyleRun> = emptyList(),
    val checklist: List<ChecklistItem> = emptyList(),
    val drawingPngBase64: String? = null,
    val color: NoteColor = NoteColor.NONE,
    val createdAt: Long = System.currentTimeMillis(),
    val updatedAt: Long = System.currentTimeMillis(),
    val pinned: Boolean = false,
    val archived: Boolean = false,
    val magicEffectId: String? = null
) {
    val isChecklist: Boolean get() = checklist.isNotEmpty()
    val isDrawing: Boolean get() = drawingPngBase64 != null
}
